### ISSUE TITLE
Second crate renaming

### ISSUE THREAD

**Issue by madsmtm** [madsmtm/objc2#51]
Prerequisite of of #33.

I'm realising that using `-` over `_` is more common (though the standard is unclear, see https://github.com/rust-lang/api-guidelines/discussions/29), and the documentation explicitly recommends `-` in `-sys` crates.

But more importantly, I think the `objc2` prefixing is unnecessary. At least if the goal is to make upstream `objc` and `fruity` use `objc-sys`.

- [x] Keep `objc2`
- [x] `objc2_foundation` -> `objc2-foundation`
- [x] `objc2_sys` -> `objc-sys`
- [x] `objc2_block_sys` (see #49) -> `block-sys`
- [x] `objc2_block` -> `block2`?
- [x] `objc2_encode` -> `objc2-encode`
- [x] ~`objc2_exception` -> `objc-exception-sys`? `objc2-exception-sys`? `objc-try-catch-sys`?~ Merged into `objc2`, see #57
- [x] ~`objc2_foundation_derive`~ Removed in #56
- [x] Change `objc2_test_utils` so that we don't have to publish it
