### ISSUE TITLE
Improve `objc2::foundation`

### ISSUE THREAD

**Issue by madsmtm** [madsmtm/objc2#67]
Collection of ideas to improve `objc2-foundation`

- [x] ~Add more iterator methods to `INSArray` and `INSMutableArray`~ Moved to https://github.com/madsmtm/objc2/issues/304
- [x] Safety of `NSArray::objects_in_range` (out of bounds?)
- [x] ~Add `INSString::to_string` to avoid having to use `autoreleasepool`~ This is already available via. `Display`
- [x] Figure out how `NSNumber` vs. `NSValue` should work - done in #226
- [x] Lifetime parameter on `NSString`/`NSData` and subclasses, so that `initWithBytesNoCopy` can work?
  - I won't be doing this, the complexity penalty to the normal use-cases is just too high. If desired one can always `struct MyNSString<'a>(NSString, PhantomData<&'a >)`
- [x] `NSData` index with ranges / `SliceIndex`?
- [x] `NSSize` validity: https://github.com/madsmtm/objc2/pull/260
- [x] Iteration improvements, moved to https://github.com/madsmtm/objc2/issues/304

Add these classes/structs that are used by `winit`:
- [x] `NSThread`
- [x] `NSString`
- [x] `NSAttributedString`
- [x] `NSAttributedMutableString`
- [x] `NSArray`
- [x] `NSProcessInfo`
- [x] `NSDictionary`
- [x] `NSData`
- [x] `NSFastEnumeration`
- [x] `NSNotificationCenter`
- [x] `NSTimeInterval`
- [x] `NSPoint`
- [x] `NSRect`
- [x] `NSSize`
- [x] `NSRange`

An furthermore these that are available in `cocoa-foundation`:
- [x] `NSOperatingSystemVersion`
- [x] More `NSProcessInfo` methods
- [x] `NSEnumerationOptions`?
- [x] `NSDate`
- [x] `NSRunLoop`
- [x] `NSURL`
- [x] `NSBundle`
- [x] `NSData` base64 functionality?
- [x] `NSUserDefaults`

And a few that makes sense to do:
- [x] `NSSet`/`NSMutableSet` - https://github.com/madsmtm/objc2/pull/245
- [x] `NSMutableDictionary` - https://github.com/madsmtm/objc2/pull/249 

And many more, since https://github.com/madsmtm/objc2/pull/264

**Comment by madsmtm** [comment]
Fixed by https://github.com/madsmtm/objc2/pull/308
